
ResultantFolder='/cbica/home/zhouz/projects/istaging/LiHM_NMF/scripts/NMF_steps/step_3';

cmd = ['matlab -nosplash -nodesktop -r ' ...
               '"load(''' ResultantFolder '/Configuration.mat''),' ...
               'deployFuncMvnmfL21p1_func_vol_single(sbjListFile,sbjTCFolder,maskFile,' ...
               'prepDataFile,ResultantFolder,resId,initName,K,alphaS21,' ...
               'alphaL,vxI,spaR,ard,eta,iterNum,calcGrp,parforOn),exit(1)">"' ...
               ResultantFolder '/ParcelFinal.log" 2>&1'];
cmd
           
sbjListFile = '123';
cmd2 = sprintf('./deployFuncMvnmfL21p1_func_vol_single.sh /cbica/software/external/matlab/R2018A "%s" ${sbjTCFile} ${maskFile} ${prepDataFile} ${outDir} ${resId} ${init_file} ${K} ${alphaS21} ${alphaL} ${vxI} ${spaR} ${ard} ${eta} ${iNum} ${calcGrp} ${parforOn} ${sub_ID} > %s/ParcelFinal.log 2>&1', '123',ResultantFolder);
cmd3 = "./deployFuncMvnmfL21p1_func_vol_single.sh /cbica/software/external/matlab/R2018A '"+ sbjListFile+"'";
cmd3
